// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xterxkgafndgmwskdneu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0ZXJ4a2dhZm5kZ213c2tkbmV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODI3NzcsImV4cCI6MjA2OTk1ODc3N30.5ZPL3GyrsUJKQ9IOi7uqnTVDC5pFEMV5M3APdXVDUTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});